# Generated by Django 4.2.1 on 2023-06-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.TextField(verbose_name='Source Text')),
                ('source_lang', models.CharField(max_length=50, verbose_name='Source Language')),
                ('target_lang', models.CharField(max_length=50, verbose_name='Target Language')),
                ('translation', models.TextField(verbose_name='Translated Text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Translation',
                'verbose_name_plural': 'Translations',
            },
        ),
    ]
